version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "axone-protocol/maintainers"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "axone-protocol/maintainers"
