import type { Metadata } from 'next';
import { Courier_Prime } from 'next/font/google';
import './globals.css';
import Header from '@/components/ui/header';
import Sidebar from '@/components/ui/sidebar';

const font = Courier_Prime({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} bg-axone-bg-dark`}>
        <main className='flex w-full h-screen'>
          <Sidebar />
          <div className='w-full h-screen overflow-y-auto'>
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
